#!/bin/bash
 
JOKE=`curl -s "http://www.jokes4us.com/yomamajokes/random/yomama`echo $(( ( RANDOM % 1192 )  + 1 ))`.html" | grep -i "^Yo" | sed 's/<br>//g' | sed 's/<\/p>//g' | sed 's/&quot;//g'`

say "$JOKE HA HA HA HA"
