#!/bin/bash
 
JOKE=`curl -s http://www.yomamajokes247.com/random-yo-mama-jokes.html | grep "<p>Yo" | sed -e 's/&#039;//g' -e 's/<p>//g' -e 's/\/p//g' -e 's/<>//g' -e 's/<br \/>//g' -e 's/&quot;//g'`

say "$JOKE HA HA HA HA"
